version: "3"
services:
  db:
    image: debezium/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kinguru
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: kinguru
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3.2.Final
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: quay.io/debezium/kafka:2.3.2.Final
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: 'false'
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      http.cors.allow-origin: "*"
      http.cors.enabled: true
      http.cors.allow-credentials: true
      http.cors.allow-methods: OPTIONS, POST
      http.cors.allow-headers: x-elastic-client-meta, X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
  connect:
    image: debezium/connect-jdbc-es:2.3.2.Final
    build:
      context: .docker
      args:
        DEBEZIUM_VERSION: 2.3.2.Final
    ports:
      - "8083:8083"
      - "5005:5005"
    links:
      - kafka
      - db
      - elastic
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"