version: "3"
services:
  db:
    image: debezium/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kinguru
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: kinguru
  zookeeper:
    image: quay.io/debezium/zookeeper:2.5.3.Final
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: quay.io/debezium/kafka:2.5.3.Final
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: 'false'
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      http.cors.enabled: true
      http.cors.allow-credentials: true
      http.cors.allow-methods: OPTIONS, POST
      http.cors.allow-headers: x-elastic-client-meta, X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
  connect:
    build:
      context: .docker
    ports:
      - "8083:8083"
      - "5005:5005"
    links:
      - kafka
      - db
      - elastic
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
