### Create connector PSQL
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "inventory-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "database.hostname": "db",
    "database.port": "5432",
    "database.user": "kinguru",
    "database.password": "qwerty",
    "database.dbname": "kinguru",
    "database.server.name": "kinguru",
    "table.include.list": "public.Event,public.User,public.Place,public.Premise,public.PremiseSlot",
    "topic.prefix": "kinguru",
    "transforms": "unwrap",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "transforms.unwrap.drop.tombstones": "false"
  }
}

### Create ES index
GET http://localhost:9200/_cat/indices

### Get mappings
GET http://localhost:9200/kinguru.public.premise_fulfilled/_mappings
Content-Type: application/json

### Get es content
GET http://localhost:9200/kinguru.public.premise_fulfilled/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "booked_slots": "premise"
          }
        }
      ]
    }
  }
}

### Get es content
GET https://localhost:9202/kinguru.public.premise_fulfilled/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": []
    }
  }
}

### Update PSQL connector
PUT http://localhost:8083/connectors/inventory-connector/config
Content-Type: application/json

{
  "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  "database.hostname": "db",
  "database.port": "5432",
  "database.user": "postgres",
  "database.password": "qwerty",
  "database.dbname": "postgres",
  "database.server.name": "kinguru",
  "table.include.list": "public.Event,public.Premise,public.PremiseSlot",
  "topic.prefix": "kinguru",
  "transforms": "unwrap",
  "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
  "transforms.unwrap.drop.tombstones": "false"
}

### Delete PSQL connector
DELETE http://localhost:8083/connectors/inventory-connector

### Delete ES premise_fulfilled index
DELETE http://localhost:9200/kinguru.public.premise_fulfilled
