-- AlterTable
ALTER TABLE "Place" ADD COLUMN     "ageRestrictions" TEXT NOT NULL DEFAULT '+4',
ADD COLUMN     "amenities" TEXT[],
ADD COLUMN     "area" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "billingMapboxId" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "cameraOrAudioRecording" BOOLEAN,
ADD COLUMN     "cleaningFeePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "description" TEXT NOT NULL DEFAULT 'Description',
ADD COLUMN     "hasWifi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "locationMapboxId" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "maxCapacity" INTEGER,
ADD COLUMN     "minCapacity" INTEGER,
ADD COLUMN     "parkingArea" TEXT[],
ADD COLUMN     "rentalPriceByHour" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "routeToPremises" TEXT,
ADD COLUMN     "rules" TEXT DEFAULT 'Rules',
ADD COLUMN     "title" TEXT NOT NULL DEFAULT 'Place',
ADD COLUMN     "wifiLogin" TEXT,
ADD COLUMN     "wifiPassword" TEXT;
