"use client";

import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Container,
  Heading,
  ListItem,
  Text,
  UnorderedList,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GetStaticPropsContext } from "next/types";
import { useTranslations } from "next-intl";
import { staticPaths } from "@/navigation.ts";
import logo from "~/public/img/logo_rounded.png";

export default function PrivacyPolicyPage() {
  const t = useTranslations();
  return (
    <Container maxW={["full", "80%", "70%", "50%"]} py={10}>
      <Head>
        <title>{t("metadata.cookie.title")}</title>
        <meta name="description" content={t("metadata.cookie.description")} />
        <meta property="og:title" content={t("metadata.cookie.title")} />
        <meta
          property="og:description"
          content={t("metadata.cookie.description")}
        />
        <meta property="og:image" content="https://kinguru.io/img/brand.png" />
      </Head>
      <VStack>
        <Image
          src={logo}
          alt={"Kinguru"}
          style={{ margin: "auto" }}
          width={150}
        />
        <Heading textAlign={"center"}>Cookie Policy</Heading>
        <Text textAlign={"center"}>Updated at 2023-11-22</Text>
      </VStack>
      <VStack mt={10} alignItems={"flex-start"}>
        <Heading>Contact Us</Heading>
        <Text>Don't hesitate to contact us if you have any questions.</Text>
        <UnorderedList>
          <ListItem>
            Via Email:{" "}
            <Link href={"mailto:t.yarosh@kinguru.io"}>t.yarosh@kinguru.io</Link>
          </ListItem>
          <ListItem>
            Via Phone Number:{" "}
            <Link href={"tel:+48792665092"}>+48792665092</Link>
          </ListItem>
        </UnorderedList>
      </VStack>
      <Accordion mt={10} allowMultiple>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Definitions and key terms
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              To help explain things as clearly as possible in this Cookie
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </Text>
            <UnorderedList>
              <ListItem>
                Cookie: small amount of data generated by a website and saved by
                your web browser. It is used to identify your browser, provide
                analytics, remember information about you such as your language
                preference or login information.
              </ListItem>
              <ListItem>
                Company: when this policy mentions “Company,” “we,” “us,” or
                “our,” it refers to JDG Tatsiana Yarash, (Poland, Zielonka,
                Literacka 40A, lok.1), that is responsible for your information
                under this Privacy Policy.
              </ListItem>
              <ListItem>
                Device: any internet connected device such as a phone, tablet,
                computer or any other device that can be used to visit KINGURU
                and use the services.
              </ListItem>
              <ListItem>
                IP address: Every device connected to the Internet is assigned a
                number known as an Internet protocol (IP) address. These numbers
                are usually assigned in geographic blocks. An IP address can
                often be used to identify the location from which a device is
                connecting to the Internet.
              </ListItem>
              <ListItem>
                Personal Data: any information that directly, indirectly, or in
                connection with other information — including a personal
                identification number — allows for the identification or
                identifiability of a natural person.
              </ListItem>
              <ListItem>
                Service: refers to the service provided by KINGURU as described
                in the relative terms (if available) and on this platform.
              </ListItem>
              <ListItem>
                Third-party service: refers to advertisers, contest sponsors,
                promotional and marketing partners, and others who provide our
                content or whose products or services we think may interest you.
              </ListItem>
              <ListItem>
                Website: KINGURU’s site, which can be accessed via this URL:
                kinguru.io
              </ListItem>
            </UnorderedList>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Introduction
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              This Cookie Policy explains how kinguru and its affiliates
              (collectively "kinguru", "we", "us", and "ours"), use cookies and
              similar technologies to recognize you when you visit our website,
              including without limitation kinguru.io and any related URLs,
              mobile or localized versions and related domains / sub-domains
              ("Websites"). It explains what these technologies are and why we
              use them, as well as the choices for how to control them.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              What is a cookie?
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              A cookie is a small text file that is stored on your computer or
              other internet connected device in order to identify your browser,
              provide analytics, remember information about you such as your
              language preference or login information. They're completely safe
              and can't be used to run programs or deliver viruses to your
              device.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Why do we use cookies?
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              We use first party and/or third party cookies on our website for
              various purposes such as:
            </Text>
            <UnorderedList>
              <ListItem>
                To facilitate the operation and functionality of our website;
              </ListItem>
              <ListItem>
                To improve your experience of our website and make navigating
                around them quicker and easier;
              </ListItem>
              <ListItem>
                To allow us to make a bespoke user experience for you and for us
                to understand what is useful or of interest to you;
              </ListItem>
              <ListItem>
                To analyze how our website is used and how best we can customize
                it;
              </ListItem>
              <ListItem>
                To identify future prospects and personalize marketing and sales
                interactions with it;
              </ListItem>
              <ListItem>
                To facilitate the tailoring of online advertising to your
                interests.
              </ListItem>
              <ListItem>
                You: a person or entity that is registered with kinguru to use
                the Services.
              </ListItem>
            </UnorderedList>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              What type of cookies does KINGURU use?
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              Cookies can either be session cookies or persistent cookies. A
              session cookie expires automatically when you close your browser.
              A persistent cookie will remain until it expires or you delete
              your cookies. Expiration dates are set in the cookies themselves;
              some may expire after a few minutes while others may expire after
              multiple years. Cookies placed by the website youâ€™re visiting
              are called â€œfirst party cookiesâ€. Strictly Necessary cookies
              are necessary for our website to function and cannot be switched
              off in our systems. They are essential in order to enable you to
              navigate around the website and use its features. If you remove or
              disable these cookies, we cannot guarantee that you will be able
              to use our website. We use the following types of cookies in our
              website:
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Essential Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              We use essential cookies to make our website work. These cookies
              are strictly necessary to enable core functionality such as
              security, network management, your cookie preferences and
              accessibility. Without them you wouldn't be able to use basic
              services. You may disable these by changing your browser settings,
              but this may affect how the Websites function.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Performance and Functionality Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              These cookies are used to enhance the performance and
              functionality of our website but are non-essential to their use.
              However, without these cookies, certain functionality like videos
              may become unavailable or you would be required to enter your
              login details every time you visit the website as we would not be
              able to remember that you had logged in previously.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Marketing Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              These account-based marketing cookies enable us to identify future
              prospects and personalize sales and marketing interactions with
              them.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Analytics and Customization Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              These cookies collect information that is used to help us
              understand how our website is being used or how effective our
              marketing campaigns are, or to help us customize our website for
              you. We use cookies served by Google Analytics to collect limited
              data directly from end-user browsers to enable us to better
              understand your use of our website. Further information on how
              Google collects and uses this data can be found at:Â
              https://www.google.com/policies/privacy/partners/. You can opt-out
              of all Google supported analytics on our Websites by visiting:Â
              https://tools.google.com/dlpage/gaoptout.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Social Media Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              These cookies are used when you share information using a social
              media sharing button or â€œlikeâ€ button on our Site or you link
              your account or engage with our content on or through a social
              networking website such as Facebook, Twitter or Google+. The
              social network will record that you have done this. These cookies
              may also include certain code that has been placed on the platform
              to help track conversions from ads, optimize ads based on
              collected data, build targeted audiences for future ads, and
              remarket to qualified users who have already taken certain action
              on the platform.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Third Party Cookies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              Some cookies that have been set on our website are not set on a
              first party basis by kinguru. The Websites can be embedded with
              content from third parties to serve advertising. These third party
              service providers may set their own cookies on your web browser.
              Third party service providers control many of the performance and
              functionality, advertising, marketing and analytics cookies
              described above. We do not control the use of these third party
              cookies as cookies can only be accessed by the third party that
              originally set them.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              How you can manage cookies?
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              Most browsers allow you to control cookies through their
              'settings' preferences. However, if you limit the ability of
              websites to set cookies, you may worsen your overall user
              experience, since it will no longer be personalized to you. It may
              also stop you from saving customized settings like login
              information. Browser manufacturers provide help pages relating to
              cookie management in their products. Browser manufacturers provide
              help pages relating to cookie management in their products. Please
              see below for more information.
            </Text>
            <UnorderedList>
              <ListItem>Google Chrome</ListItem>
              <ListItem>Internet Explorer</ListItem>
              <ListItem>Mozilla Firefox</ListItem>
              <ListItem>Safari (Desktop)</ListItem>
              <ListItem>Safari (Mobile)</ListItem>
              <ListItem>Android Browser</ListItem>
              <ListItem>Opera</ListItem>
              <ListItem>Opera Mobile</ListItem>
            </UnorderedList>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Blocking and disabling cookies and similar technologies
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              Wherever you're located you may also set your browser to block
              cookies and similar technologies, but this action may block our
              essential cookies and prevent our website from functioning
              properly, and you may not be able to fully utilize all of its
              features and services. You should also be aware that you may also
              lose some saved information (e.g. saved login details, site
              preferences) if you block cookies on your browser. Different
              browsers make different controls available to you. Disabling a
              cookie or category of cookie does not delete the cookie from your
              browser, you will need to do this yourself from within your
              browser, you should visit your browser's help menu for more
              information.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Changes To Our Cookie Policy
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              We may change our Service and policies, and we may need to make
              changes to this Cookie Policy so that they accurately reflect our
              Service and policies. Unless otherwise required by law, we will
              notify you (for example, through our Service) before we make
              changes to this Cookie Policy and give you an opportunity to
              review them before they go into effect. Then, if you continue to
              use the Service, you will be bound by the updated Cookie Policy.
              If you do not want to agree to this or any updated Cookie Policy,
              you can delete your account.
            </Text>
          </AccordionPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionButton>
            <Box as="span" flex="1" textAlign="left">
              Your Consent
            </Box>
            <AccordionIcon />
          </AccordionButton>
          <AccordionPanel pb={4}>
            <Text>
              By using our website, registering an account, or making a
              purchase, you hereby consent to our Cookie Policy and agree to its
              terms.
            </Text>
          </AccordionPanel>
        </AccordionItem>
      </Accordion>
    </Container>
  );
}

export async function getStaticProps({ params }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`~/public/locales/${params?.locale}/common.json`))
        .default,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: staticPaths,
    fallback: false,
  };
}
