export const keywordsEN = [
  "eventify",
  "event",
  "event management",
  "online events",
  "event platform",
  "conferences",
  "workshops",
  "webinars",
  "virtual events",
  "event planning",
  "corporate events",
  "hybrid events",
  "live streaming",
  "networking events",
  "ticketing system",
  "event registration",
  "digital events",
  "expo management",
  "business networking",
  "conference software",
  "event technology",
  "virtual summit",
  "event hosting",
  "community engagement",
  "online ticket sales",
  "guest management",
  "event marketing",
  "event engagement tools",
  "event apps",
  "event sponsorships",
  "event analytics",
  "event promotion",
  "event branding",
  "event ticketing",
  "event software",
  "event production",
  "conference management",
  "online conference platform",
  "event livestreaming",
  "event tools",
  "meeting planning",
  "event audience management",
  "team collaboration tools",
  "online expo",
  "convention management",
  "virtual event platform",
  "event hosting platform",
  "corporate meeting tools",
  "event logistics",
  "event budget management",
  "event attendee engagement",
  "event networking solutions",
  "interactive events",
  "event video streaming",
  "event participation",
  "event app integration",
  "audience interaction tools",
  "custom event branding",
  "event sponsorship opportunities",
  "on-demand events",
  "event gamification",
  "event ticket management",
  "attendee experience",
  "personalized event experiences",
  "event platform integrations",
  "on-site event services",
  "event strategy",
  "event exhibitors",
  "event VIP management",
  "event accessibility tools",
  "multilingual event platforms",
  "event photo booths",
  "event swag management",
  "event signage",
  "crowd engagement tools",
  "virtual trade shows",
  "event speaker management",
  "event coordination software",
  "remote event hosting",
  "corporate seminar tools",
  "event surveys and feedback",
  "event content creation",
  "event partnerships",
  "real-time event analytics",
  "event video conferencing",
  "event sponsorship packages",
  "event audience segmentation",
  "event live polling",
  "event breakouts",
  "event ticket distribution",
  "event cloud solutions",
  "remote networking events",
  "event sustainability",
  "event gamification platforms",
  "virtual conference experiences",
  "event mobile apps",
  "personalized event invites",
  "attendee matchmaking",
  "event QR codes",
  "event feedback collection",
  "seamless event check-in",
  "event experience management",
];

export const keywordsPL = [
  "eventify",
  "event",
  "zarządzanie wydarzeniami",
  "wydarzenia online",
  "platforma eventowa",
  "konferencje",
  "warsztaty",
  "webinary",
  "wydarzenia wirtualne",
  "planowanie wydarzeń",
  "wydarzenia korporacyjne",
  "wydarzenia hybrydowe",
  "streaming na żywo",
  "wydarzenia networkingowe",
  "system biletowy",
  "rejestracja na wydarzenia",
  "wydarzenia cyfrowe",
  "zarządzanie wystawą",
  "networking biznesowy",
  "oprogramowanie konferencyjne",
  "technologie wydarzeń",
  "wirtualny szczyt",
  "organizacja wydarzeń",
  "zaangażowanie społeczności",
  "sprzedaż biletów online",
  "zarządzanie gośćmi",
  "marketing wydarzeń",
  "narzędzia zaangażowania w wydarzenia",
  "aplikacje wydarzeniowe",
  "sponsoring wydarzeń",
  "analityka wydarzeń",
  "promocja wydarzeń",
  "brandowanie wydarzeń",
  "bilety na wydarzenia",
  "oprogramowanie do wydarzeń",
  "produkcja wydarzeń",
  "zarządzanie konferencjami",
  "platforma konferencyjna online",
  "streaming wydarzeń",
  "narzędzia wydarzeniowe",
  "planowanie spotkań",
  "zarządzanie uczestnikami wydarzenia",
  "narzędzia współpracy zespołowej",
  "wystawa online",
  "zarządzanie konwencjami",
  "platforma wydarzeń wirtualnych",
  "platforma organizacji wydarzeń",
  "narzędzia do spotkań korporacyjnych",
  "logistyka wydarzeń",
  "zarządzanie budżetem wydarzenia",
  "zaangażowanie uczestników wydarzeń",
  "rozwiązania networkingowe w wydarzeniach",
  "interaktywne wydarzenia",
  "streaming wideo wydarzeń",
  "udział w wydarzeniach",
  "integracja aplikacji wydarzeń",
  "narzędzia interakcji z uczestnikami",
  "brandowanie wydarzeń na zamówienie",
  "okazje sponsoringowe w wydarzeniach",
  "wydarzenia na żądanie",
  "grywalizacja wydarzeń",
  "zarządzanie biletami na wydarzenia",
  "doświadczenie uczestnika",
  "spersonalizowane doświadczenia wydarzeń",
  "integracje platformy wydarzeń",
  "usługi wydarzeń na miejscu",
  "strategia wydarzeń",
  "wystawcy wydarzeń",
  "zarządzanie VIP-ami wydarzeń",
  "narzędzia dostępności wydarzeń",
  "wielojęzyczne platformy wydarzeń",
  "budki fotograficzne na wydarzenia",
  "zarządzanie upominkami z wydarzeń",
  "oznakowanie wydarzeń",
  "narzędzia zaangażowania tłumu",
  "wirtualne targi",
  "zarządzanie prelegentami wydarzeń",
  "oprogramowanie koordynacji wydarzeń",
  "organizacja wydarzeń zdalnych",
  "narzędzia seminariów korporacyjnych",
  "ankiety i opinie wydarzeń",
  "tworzenie treści wydarzeń",
  "partnerstwa wydarzeń",
  "analityka wydarzeń w czasie rzeczywistym",
  "wideokonferencje wydarzeń",
  "pakiety sponsorskie wydarzeń",
  "segmentacja publiczności wydarzeń",
  "głosowanie na wydarzenia",
  "przerwy podczas wydarzeń",
  "dystrybucja biletów na wydarzenia",
  "rozwiązania w chmurze dla wydarzeń",
  "wydarzenia networkingowe zdalne",
  "zrównoważony rozwój wydarzeń",
  "platformy grywalizacji wydarzeń",
  "wirtualne doświadczenia konferencyjne",
  "aplikacje mobilne wydarzeń",
  "spersonalizowane zaproszenia na wydarzenia",
  "dopasowanie uczestników",
  "kody QR na wydarzenia",
  "zbieranie opinii z wydarzeń",
  "płynna rejestracja na wydarzenia",
  "zarządzanie doświadczeniem wydarzeń",
];
