import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { NotoSans } from "@/fontLoader.ts";
import { css } from "~/styled-system/css";

import "../globals.css";
import { Box } from "~/styled-system/jsx";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  return (
    <html lang={locale} className={`${NotoSans.variable}`}>
      <body className={css({ fontFamily: "noto" })}>
        <Box minHeight="100vh">
          <Header />
          <main className={css({ height: 0, minHeight: "calc(100vh - 85px)" })}>
            {children}
          </main>
        </Box>
        <Footer />
      </body>
    </html>
  );
}
