import { NextIntlClientProvider, useMessages } from "next-intl";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { NotoSans } from "@/fontLoader.ts";
import { css } from "~/styled-system/css";
import { Box } from "~/styled-system/jsx";

import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  const messages = useMessages();

  return (
    <html lang={locale} className={`${NotoSans.variable}`}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className={css({ fontFamily: "noto" })}>
          <Box minHeight="100vh">
            <Header />
            <main
              className={css({ height: 0, minHeight: "calc(100vh - 85px)" })}
            >
              {children}
            </main>
          </Box>
          <Footer />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
