apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-tls
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
    - hosts:
        - {{ $.Values.ingress.hostname }}
      secretName: {{ .Chart.Name }}-letsencrypt-{{ .Values.werf.env }}
  rules:
    - host: {{ $.Values.ingress.hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: 3000
