apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration-job
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migration
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: {{ .Values.werf.image.kinguru }}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/ash", "-c", "--" ]
          args: [ "cd app && npx prisma migrate deploy" ]
          envFrom:
            - secretRef:
                name: kr-prod-environment-vars