image:
  pullSecret: __PULL_SECRET__

ingress:
  hostname: __HOSTNAME__

defaultReplicas: 2

environment: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi