image:
  pullSecret: __PULL_SECRET__

ingress:
  hostname: __HOSTNAME__

replicas:
  default: 2
  min: 1
  max: 5

environment: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi

schedulerResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi

redisResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi