name: staging migration reset
on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write
      packages: write
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install werf
        uses: werf/actions/install@v1.2
      - name: Run deployment
        run: |
          . $(werf ci-env github --as-file)
          werf cr login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          werf kube-run kinguru -- prisma migrate reset --force
        env:
          WERF_ENV: staging
          WERF_SET_1: image.pullSecret=github-cr-secret
          WERF_SET_2: ingress.hostname=staging.eventify.today
          WERF_SET_3: replicas.default=1
          WERF_SET_4: replicas.min=1
          WERF_SET_5: replicas.max=2
          SITE_URL: https://staging.eventify.today
          DATABASE_URL: ${{ secrets.DB_URL }}
          NEXT_PUBLIC_GA_ID: ${{ secrets.GA_ID }}
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          NEXT_PUBLIC_ELASTICSEARCH_API_KEY: ${{ secrets.ELASTICSEARCH_API_KEY }}
          NEXT_PUBLIC_ELASTICSEARCH_ENDPOINT: ${{ secrets.ELASTICSEARCH_ENDPOINT }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
