name: release
on:
  push:
    branches:
      - main
jobs:
  semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: release
        run: >-
          for dir in ".helm" "." ; do
            pushd $dir; npx semantic-release-plus; popd
          done
  werf:
    runs-on: ubuntu-latest
    needs:
      - semver
    environment: prod
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: vbem/kubeconfig4sa@v1
        with:
          server: https://b6ca91f2-516c-4882-90fe-b232d3b2b33b.api.k8s.pl-waw.scw.cloud:6443
          ca-base64: ${{ secrets.K8S_CA_BASE64 }}
          token: ${{ secrets.K8S_SA_TOKEN }}
          namespace: persistence
      - uses: vbem/k8s-port-forward@v1
        with:
          workload: svc/postgres-cluster
          mappings: 5432:5432
      - name: Install werf
        uses: werf/actions/install@v1.2
      - name: Run deployment
        run: |
          . $(werf ci-env github --as-file)
          werf cr login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          werf converge --atomic
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
          WERF_ENV: prod
          WERF_SET_1: image.pullSecret=github-cr-secret
          WERF_SET_2: ingress.hostname=v2.kinguru.io
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          NEXT_PUBLIC_ELASTICSEARCH_API_KEY: ${{ secrets.ELASTICSEARCH_API_KEY }}
          NEXT_PUBLIC_ELASTICSEARCH_ENDPOINT: ${{ secrets.ELASTICSEARCH_ENDPOINT }}
