name: Build & deploy Storybook
on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: storybook
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          install_command: npm i